# Use the official Shiny image
FROM rocker/shiny:latest

# Install required R packages
RUN install2.r --error --skipinstalled \
    auth0 \
    shiny \
    shinyjs \
    tidyverse \
    readxl \
    openxlsx \
    yaml

# Copy your Shiny app into the container
COPY . /srv/shiny-server/

# Make sure auth0.yml is in the same directory as app.R
COPY auth0.yml /srv/shiny-server/auth0.yml

# Optional: log to stdout for easier debugging in Portainer
ENV APPLICATION_LOGS_TO_STDOUT=true

# Expose the default Shiny port
EXPOSE 3838
